
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.math.*;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.ImageIcon;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Esada
 */
public class MainFrame extends javax.swing.JFrame {

    private final IntegerGCD g = new IntegerGCD();
    private final BigIntegerGCD gB = new BigIntegerGCD();
    private ArrayList<Result> alBigIn = new ArrayList<>();
    private ArrayList<String> alIn = new ArrayList<>();
    private int min;
    private int max;
    private File currentFile = new File(System.getProperty("user.dir"));
    
    public Object[] BigInToArray() {
        return alBigIn.toArray();

    }

    public Object[] InToArray() {

        return alIn.toArray();

    }
    
    
     public int Firstnum() {
        int a = Integer.valueOf(num1TextField.getText());
        if(a<= 2147483647){
        return a;
        }else{
        ImageIcon iconic=new ImageIcon("Esadaa.png");
        JOptionPane.showMessageDialog(null, "The numebr is to Big, please choose a smaller number", "Error", JOptionPane.ERROR_MESSAGE,iconic);
        }
        return 0;
    }
    public int SecondNum() {
        int b = Integer.valueOf(num2TextField.getText());
        
        if(b<= 2147483647){
        return b;
        }else{
        ImageIcon iconic=new ImageIcon("Esadaa.png");
        JOptionPane.showMessageDialog(null, "The numebr is to Big, please choose a smaller number", "Error", JOptionPane.ERROR_MESSAGE,iconic);
        }
        return 0;
        
    }

    public BigInteger DigitNumBig() {
        int x = Integer.valueOf(BigNumTextField.getText());

        BigInteger max = (BigInteger) (BigInteger.TEN.pow(x)).subtract(BigInteger.ONE);
        BigInteger min = (BigInteger) (BigInteger.TEN.pow(x - 1));
        BigInteger delta = max.subtract(min);
        Random rnd = new Random();
        BigInteger n1 = new BigInteger(delta.bitLength(), rnd);

        do {
            n1 = new BigInteger(delta.bitLength(), rnd);
        } while (n1.compareTo(delta) > 0);

        return n1.add(min);

    }

    public ArrayList<Result> loadFromCSV(String fileName) throws IOException {
        try ( BufferedReader in = new BufferedReader(new FileReader(fileName))) {
            String l = in.readLine();
            ArrayList<Result> alResults = new ArrayList<>();
            while ((l = in.readLine()) != null) {
                String[] ar = l.split(";");
                alResults.add(new Result(BigInteger.valueOf(Long.valueOf(ar[2])),BigInteger.valueOf(Long.valueOf(ar[1])),BigInteger.valueOf(Long.valueOf(ar[3])),Double.valueOf(ar[4]),ar[0]));
            }
            return alResults;
        }
    }
    
    public void saveToCSV(String fileName, ArrayList<Result> alResults) throws IOException {
        try ( PrintWriter out = new PrintWriter(new FileWriter(fileName))) {
            out.println("Algorithms;First_number;Second_number;gcd;Time");
            for (Result x : alResults) {
                out.println(x.toCSV());
            }
        }
    }

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {

        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EucButton = new javax.swing.JButton();
        ExEucButton = new javax.swing.JButton();
        BinButton = new javax.swing.JButton();
        EucBigButton = new javax.swing.JButton();
        ExEucBigButton = new javax.swing.JButton();
        BinBigButton = new javax.swing.JButton();
        ExBinButton = new javax.swing.JButton();
        ExBinBigButton = new javax.swing.JButton();
        selfBigGcdButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewList = new javax.swing.JList();
        removeBigInButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList();
        removeInButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BigNumTextField = new javax.swing.JTextField();
        clearjlistButton = new javax.swing.JButton();
        clearviewlistButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        numLabel = new javax.swing.JLabel();
        denLabel = new javax.swing.JLabel();
        num1TextField = new javax.swing.JTextField();
        num2TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EucButton.setBackground(new java.awt.Color(204, 255, 204));
        EucButton.setText("Euc");
        EucButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EucButtonActionPerformed(evt);
            }
        });

        ExEucButton.setBackground(new java.awt.Color(102, 255, 204));
        ExEucButton.setText("ExEuc");
        ExEucButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExEucButtonActionPerformed(evt);
            }
        });

        BinButton.setBackground(new java.awt.Color(255, 204, 204));
        BinButton.setText("Bin");
        BinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinButtonActionPerformed(evt);
            }
        });

        EucBigButton.setBackground(new java.awt.Color(204, 255, 204));
        EucBigButton.setText("EucBig");
        EucBigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EucBigButtonActionPerformed(evt);
            }
        });

        ExEucBigButton.setBackground(new java.awt.Color(102, 255, 204));
        ExEucBigButton.setText("ExEucBig");
        ExEucBigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExEucBigButtonActionPerformed(evt);
            }
        });

        BinBigButton.setBackground(new java.awt.Color(255, 204, 204));
        BinBigButton.setText("BinBig");
        BinBigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinBigButtonActionPerformed(evt);
            }
        });

        ExBinButton.setBackground(new java.awt.Color(204, 204, 255));
        ExBinButton.setText("ExBin");
        ExBinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExBinButtonActionPerformed(evt);
            }
        });

        ExBinBigButton.setBackground(new java.awt.Color(204, 204, 255));
        ExBinBigButton.setText("ExBinBig");
        ExBinBigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExBinBigButtonActionPerformed(evt);
            }
        });

        selfBigGcdButton.setBackground(new java.awt.Color(204, 204, 0));
        selfBigGcdButton.setText("selfBigGcd");
        selfBigGcdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selfBigGcdButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(viewList);

        removeBigInButton.setBackground(new java.awt.Color(204, 204, 204));
        removeBigInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Knob-Remove-Red-icon klein.png"))); // NOI18N
        removeBigInButton.setText("Remove");
        removeBigInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBigInButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList);

        removeInButton.setBackground(new java.awt.Color(204, 204, 204));
        removeInButton.setForeground(new java.awt.Color(0, 51, 51));
        removeInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Knob-Remove-Red-icon klein.png"))); // NOI18N
        removeInButton.setText("Remove");
        removeInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeInButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Number of digits :");

        clearjlistButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Knob-Cancel-icon klein.png"))); // NOI18N
        clearjlistButton.setText("clear");
        clearjlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearjlistButtonActionPerformed(evt);
            }
        });

        clearviewlistButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Knob-Cancel-icon klein.png"))); // NOI18N
        clearviewlistButton.setText("clear");
        clearviewlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearviewlistButtonActionPerformed(evt);
            }
        });

        loadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Excel-2-icon.png"))); // NOI18N
        loadButton.setText("load (Excel)");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Excel-2-icon.png"))); // NOI18N
        saveButton.setText("save (Excel)");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        numLabel.setText("Number1:");

        denLabel.setText("Number2:");

        jLabel2.setText("BIGINTEGER");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel4.setText("INTEGER");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(321, 321, 321)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(removeBigInButton)
                                    .addComponent(loadButton))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(removeInButton)
                                .addGap(28, 28, 28)
                                .addComponent(clearjlistButton)
                                .addGap(161, 161, 161)
                                .addComponent(numLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(denLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EucBigButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(ExEucBigButton)
                                .addGap(83, 83, 83)
                                .addComponent(BinBigButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(ExBinBigButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selfBigGcdButton))
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(saveButton)
                                        .addGap(424, 424, 424))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(clearviewlistButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BigNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EucButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(ExEucButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(149, 149, 149)
                                .addComponent(BinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ExBinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EucButton)
                    .addComponent(ExEucButton)
                    .addComponent(BinButton)
                    .addComponent(ExBinButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeInButton)
                    .addComponent(clearjlistButton)
                    .addComponent(numLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(denLabel)
                    .addComponent(num2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EucBigButton)
                    .addComponent(ExEucBigButton)
                    .addComponent(BinBigButton)
                    .addComponent(ExBinBigButton)
                    .addComponent(selfBigGcdButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeBigInButton)
                    .addComponent(clearviewlistButton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BigNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EucButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EucButtonActionPerformed
        int a = Firstnum();
        int b = SecondNum();
        if(a==0 & b==0){
            System.out.println("The numbers are to big");
        }else{
            
            double sum = 0;
            for (int i = 0; i <= 10000; i++) {
                long start = System.nanoTime();
                IntegerGCD.gcdEuc(a,b);
                long end = System.nanoTime();
                long diff = end - start;
                sum += diff;
            }
            String t = ("The Euclidean GCDalgorithm :  " + sum / 10000 + " ns for the result  " + IntegerGCD.gcdEuc(a,b) + " with the Integers " + a + " & " + b);
            alIn.add(t);
            jList.setListData(InToArray());
        }
    }//GEN-LAST:event_EucButtonActionPerformed


    private void ExEucButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExEucButtonActionPerformed
        int a = Firstnum();
        int b = SecondNum();
        if( b==0 & a==0){
            System.out.println("The numbers are to big");
        }else{
            double sum = 0;
            for (int i = 0; i <= 10000; i++) {
                long start = System.nanoTime();
                IntegerGCD.gcdExEuc(a, b, 1, 1);
                long end = System.nanoTime();
                long diff = end - start;
                sum += diff;
            }
            String t = ("The ExtendedEuclidean GCDalgorithm:  " + sum / 10000 + " ns for the result  " + IntegerGCD.gcdExEuc(a,b, 1, 1) + " with the Integers " + a + " & " + b);
            alIn.add(t);
            jList.setListData(InToArray());
        }
    }//GEN-LAST:event_ExEucButtonActionPerformed

    private void BinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinButtonActionPerformed
        int a = Firstnum();
        int b = SecondNum();
        if( b==0 & a==0){
            System.out.println("The numbers are to big");
        }else{
            double sum = 0;
            for (int i = 0; i <= 10000; i++) {
                long start = System.nanoTime();
                IntegerGCD.gcdBin(a, b);
                long end = System.nanoTime();
                long diff = end - start;
                sum += diff;
            }
            String t = ("The Binary GCDalgorithm:  " + sum / 10000 + " ns for the result  " + IntegerGCD.gcdBin(a, b) + " with the Integers " + a + " & " + b);
            alIn.add(t);
            jList.setListData(InToArray());
        }
    }//GEN-LAST:event_BinButtonActionPerformed

    private void EucBigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EucBigButtonActionPerformed
        BigInteger a = DigitNumBig();
        BigInteger b = DigitNumBig();
        double sum = 0;
        for (int i = 0; i <= 10000; i++) {
            long start = System.nanoTime();
            BigIntegerGCD.gcdEucBig(a, b);
            long end = System.nanoTime();
            long diff = end - start;
            sum += diff;
        }
        Result res=new Result(b,a,BigIntegerGCD.gcdEucBig(a, b),sum / 10000,"The Euclidean GCDalgorithm");
        
        alBigIn.add(res);
        viewList.setListData(BigInToArray());
    }//GEN-LAST:event_EucBigButtonActionPerformed

    private void BinBigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinBigButtonActionPerformed
        BigInteger a = DigitNumBig();
        BigInteger b = DigitNumBig();
        double sum = 0;
        for (int i = 0; i <= 10000; i++) {
            long start = System.nanoTime();
            BigIntegerGCD.gcdBinBig(a, b);
            long end = System.nanoTime();
            long diff = end - start;
            sum += diff;
        }
        Result res=new Result(b,a,BigIntegerGCD.gcdBinBig(a, b),sum / 10000,"The Binary GCDalgorithm");
        alBigIn.add(res);
        viewList.setListData(BigInToArray());
    }//GEN-LAST:event_BinBigButtonActionPerformed

    private void ExEucBigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExEucBigButtonActionPerformed
        BigInteger a = DigitNumBig();
        BigInteger b = DigitNumBig();
        BigInteger x = new BigInteger("1");
        BigInteger y = new BigInteger("1");
        double sum = 0;
        for (int i = 0; i <= 10000; i++) {
            long start = System.nanoTime();
            BigIntegerGCD.gcdExEucBig(a, b, x, y);
            long end = System.nanoTime();
            long diff = end - start;
            sum += diff;
        }
        Result res=new Result(b,a,BigIntegerGCD.gcdExEucBig(a, b,x,y),sum / 10000,"The ExtendedEuclidean GCDalgorithm");

        alBigIn.add(res);
        viewList.setListData(BigInToArray());
    }//GEN-LAST:event_ExEucBigButtonActionPerformed

    private void ExBinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExBinButtonActionPerformed
        int a = Firstnum();
        int b = SecondNum();
        if( b==0 & a==0){
            System.out.println("The numbers are to big");
        }else{
            double sum = 0;
            for (int i = 0; i <= 10000; i++) {
                long start = System.nanoTime();
                IntegerGCD.gcdExBin(a,b);
                long end = System.nanoTime();
                long diff = end - start;
                sum += diff;
            }
            

            String t = ("The ExtendedBinary GCDalgorithm:  " + sum / 10000 + " ns for the result  " + IntegerGCD.gcdExBin(a,b) + " with the Integers " + a + " & " + b);
            alIn.add(t);
            jList.setListData(InToArray());
        }
    }//GEN-LAST:event_ExBinButtonActionPerformed

    private void ExBinBigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExBinBigButtonActionPerformed
        BigInteger a = DigitNumBig();
        BigInteger b = DigitNumBig();

        double sum = 0;
        for (int i = 0; i <= 10000; i++) {
            long start = System.nanoTime();
            BigIntegerGCD.gcdExBinBig(a, b);
            long end = System.nanoTime();
            long diff = end - start;
            sum += diff;
        }
        Result res=new Result(b,a,BigIntegerGCD.gcdExBinBig(a, b),sum / 10000,"The ExtendedBinary GCDalgorithm");

        alBigIn.add(res);
        viewList.setListData(BigInToArray());
    }//GEN-LAST:event_ExBinBigButtonActionPerformed

    private void selfBigGcdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selfBigGcdButtonActionPerformed
        BigInteger a = DigitNumBig();
        BigInteger b = DigitNumBig();
        double sum = 0;
        for (int i = 0; i <= 10000; i++) {
            long start = System.nanoTime();
            BigIntegerGCD.gcdBigInt(a, b);
            long end = System.nanoTime();
            long diff = end - start;
            sum += diff;
        }
        Result res=new Result(b,a,BigIntegerGCD.gcdBigInt(a, b),sum / 10000,"The Java BigIntegerGcd");


        alBigIn.add(res);
        viewList.setListData(BigInToArray());
    }//GEN-LAST:event_selfBigGcdButtonActionPerformed

    private void removeBigInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBigInButtonActionPerformed
        int index = viewList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "You did not select any number to remove", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            alBigIn.remove(index);
        }
        viewList.setListData(BigInToArray());
    }//GEN-LAST:event_removeBigInButtonActionPerformed

    private void removeInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeInButtonActionPerformed
        int index = jList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "You did not select any number to remove", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            alIn.remove(index);
        }
        jList.setListData(InToArray());
    }//GEN-LAST:event_removeInButtonActionPerformed

    private void clearjlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearjlistButtonActionPerformed
        alIn.clear();
        jList.setListData(InToArray());
    }//GEN-LAST:event_clearjlistButtonActionPerformed

    private void clearviewlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearviewlistButtonActionPerformed
        alBigIn.clear();
        viewList.setListData(BigInToArray());
    }//GEN-LAST:event_clearviewlistButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        JFileChooser jFileChooser = new JFileChooser(currentFile);
        jFileChooser.setAcceptAllFileFilterUsed(false);
        jFileChooser.addChoosableFileFilter(new FileNameExtensionFilter(".CSV Files", "csv"));
        int returnVal = jFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            currentFile = jFileChooser.getSelectedFile();
            try {
                alBigIn = loadFromCSV(jFileChooser.getSelectedFile().getAbsolutePath());
                ImageIcon iconic=new ImageIcon("EsadaL.png");
                JOptionPane.showMessageDialog(null, "File has been sucessfully loaded","Message", JOptionPane.INFORMATION_MESSAGE,iconic);
            } catch (Exception e) {
                System.err.println(e);
            }
        }
        viewList.setListData(BigInToArray());
    }//GEN-LAST:event_loadButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        JFileChooser jFileChooser = new JFileChooser(currentFile);
        jFileChooser.setFileFilter(new FileNameExtensionFilter(".CSV Files", "csv"));
        int returnVal = jFileChooser.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            currentFile = jFileChooser.getSelectedFile();
            try {
                String absolutPath = jFileChooser.getSelectedFile().getAbsolutePath();
                if (!absolutPath.substring(absolutPath.length() - 4).equals(".csv")) {
                    absolutPath += ".csv";
                    currentFile = new File(absolutPath);
                }
                saveToCSV(absolutPath, alBigIn);
                ImageIcon iconic=new ImageIcon("EsadaL.png");
                JOptionPane.showMessageDialog(null, "File has been sucessfully saved","Message", JOptionPane.INFORMATION_MESSAGE,iconic);
            } catch (Exception e) {
                System.err.println(e);
            }
        }

    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BigNumTextField;
    private javax.swing.JButton BinBigButton;
    private javax.swing.JButton BinButton;
    private javax.swing.JButton EucBigButton;
    private javax.swing.JButton EucButton;
    private javax.swing.JButton ExBinBigButton;
    private javax.swing.JButton ExBinButton;
    private javax.swing.JButton ExEucBigButton;
    private javax.swing.JButton ExEucButton;
    private javax.swing.JButton clearjlistButton;
    private javax.swing.JButton clearviewlistButton;
    private javax.swing.JLabel denLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loadButton;
    private javax.swing.JTextField num1TextField;
    private javax.swing.JTextField num2TextField;
    private javax.swing.JLabel numLabel;
    private javax.swing.JButton removeBigInButton;
    private javax.swing.JButton removeInButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton selfBigGcdButton;
    private javax.swing.JList viewList;
    // End of variables declaration//GEN-END:variables

    private BigInteger rnd(BigInteger subtract) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
